@startuml Omniverse Sequence Diagram

skinparam actorStyle awesome

actor Admin
participant OmniverseFrontend
participant OmniverseAPI
database OmniverseDatabase


Admin -> OmniverseFrontend: Access admin portal
OmniverseFrontend -> OmniverseAPI: GET request
OmniverseAPI -> OmniverseDatabase: GET request

OmniverseDatabase -> OmniverseAPI: Response
OmniverseAPI -> OmniverseFrontend: Response
OmniverseFrontend -> Admin: Return HTML

Admin -> OmniverseFrontend: Add/update/delete item/category
OmniverseFrontend -> OmniverseAPI: POST/PUT/DELETE request
OmniverseAPI -> OmniverseDatabase: POST/PUT/DELETE request

OmniverseDatabase -> OmniverseAPI: Response
OmniverseAPI -> OmniverseFrontend: Response
OmniverseFrontend -> Admin: Confirmation pop-up
OmniverseFrontend -> Admin: Redirect to admin homepage



@enduml