@startuml Omniverse Usecase Diagram

skinparam actorStyle awesome

left to right direction

actor Customer
package AdminPersonnel {
    actor AdminPersonnel as m
}



rectangle Omniverse {
usecase AccessWebsite
usecase AddItemToCart
usecase RemoveItemFromCart
usecase CartCheckout
usecase BrowseCategories
usecase AddNewProducts
usecase UpdateProduct
usecase DeleteProduct

' rectangle AdminPersonnel {


Customer --> AccessWebsite
Customer --> AddItemToCart
Customer --> BrowseCategories
Customer --> RemoveItemFromCart
Customer --> CartCheckout
AdminPersonnel --> AccessWebsite
AdminPersonnel --> AddNewProducts
AdminPersonnel --> UpdateProduct
AdminPersonnel --> DeleteProduct

}
@enduml